# Generated by Django 3.1.3 on 2020-11-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201111_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('books', models.ManyToManyField(to='app01.BOOK')),
            ],
        ),
    ]
