# Generated by Django 3.1.3 on 2020-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=69),
        ),
    ]
